---
title: "SP500 and witching day"
author: "Maggie Sha"
date: "2020/11/23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quantmod)
library(RcppBDT)
library(tidyverse)
library(timeDate)
library(lubridate)
```


```{r cars}
# read sp500 data from yahoo
GSPC <- read.csv("^GSPC.csv")
```



```{r}
# get dates of witching days
for (i in 1990:2020){
  Mar <- getNthDayOfWeek(third, Fri, 3, i)
  Mar1 <- Mar-7
  Mar2 <- getNthDayOfWeek(fourth, Fri, 3, i)
  
  
  Jun <- getNthDayOfWeek(third, Fri, 6, i)
  Jun1 <- Jun-7
  Jun2 <- getNthDayOfWeek(fourth, Fri, 6, i)
  
  Sep <- getNthDayOfWeek(third, Fri, 9, i)
  Sep1 <- Sep-7
  Sep2 <- getNthDayOfWeek(fourth, Fri, 9, i)
  
  Dec <- getNthDayOfWeek(third, Fri, 12, i)
  Dec1 <- Dec-7
  Dec2 <- getNthDayOfWeek(fourth, Fri, 12, i)
  
  
  if ( i == 1990){
    quad_witching_date <- cbind.data.frame(Mar1,Mar,Mar2,Jun1,Jun,Jun2,Sep1,Sep,Sep2,Dec1,Dec,Dec2)
  }
  else{
    quad_witching_date <- rbind.data.frame(quad_witching_date, cbind.data.frame(Mar1,Mar,Mar2,Jun1,Jun,Jun2,Sep1,Sep,Sep2,Dec1,Dec,Dec2))
  }
}


quad_witching <- data.frame(day = c(quad_witching_date[,'Mar1'],quad_witching_date[,'Mar'], quad_witching_date[,'Mar2'], quad_witching_date[,'Jun1'], quad_witching_date[,'Jun'], quad_witching_date[,'Jun2'], quad_witching_date[,'Sep1'], quad_witching_date[,'Sep'], quad_witching_date[,'Sep2'], quad_witching_date[,'Dec1'], quad_witching_date[,'Dec'], quad_witching_date[,'Dec2']))
quad_witching$day<- as.Date(quad_witching$day)

```

```{r}
# only keep SP500 data which are on witching days
GSPC <- GSPC[is.element(as.Date(GSPC$Date),as.Date(quad_witching$day)),]


colnames(quad_witching) <- "Date"

# only keep 'Date' and 'Adj.Close' columns
GSPC <- GSPC[,-2:-5]
GSPC <- GSPC[-3]
GSPC$Date <- as.Date(GSPC$Date)
quad_witching$Date <- as.Date(quad_witching$Date )


# full join the SP500 data and witching days, the missing values are included as NAs
with_missing <- full_join(GSPC,quad_witching)
with_missing <- with_missing[order(with_missing$Date),]


# choose the last Friday and next Friday of each witching day
# select the corresponding date and percentage change of Adj.Close 
# seperate them into two datasets called lastF and nextF.
 for (i in 1:(nrow(with_missing)/3)) {
   l <- (with_missing$Adj.Close[i*3-1] - with_missing$Adj.Close[i*3-2]) /  with_missing$Adj.Close[i*3-2]
   n <- (with_missing$Adj.Close[i*3]-with_missing$Adj.Close[i*3-1]) /  with_missing$Adj.Close[i*3-1]
   d1 <- as.Date(with_missing$Date[i*3-2])
   d2 <- as.Date(with_missing$Date[i*3])
   if (i == 1){
      lastF <- cbind.data.frame(l)
      Date1 <- cbind.data.frame(d1)
      nextF <- cbind.data.frame(n)
      Date2 <- cbind.data.frame(d2)
    } else {
     lastF <- rbind.data.frame(lastF,cbind.data.frame(l))
     Date1 <- rbind.data.frame(Date1,cbind.data.frame(d1))
     nextF <- rbind.data.frame(nextF,cbind.data.frame(n))
     Date2 <- rbind.data.frame(Date2,cbind.data.frame(d2))
    }  
 }

Date1 <- cbind(Date1,lastF)
colnames(Date1) <- c("Date","Percentage_Change")
# write.csv(Date1,"D:\\MA675 FIDELITY\\lastF.csv", row.names = FALSE)


Date2 <- cbind(Date2,nextF)
colnames(Date2) <- c("Date","Percentage_Change")
# write.csv(Date2,"D:\\MA675 FIDELITY\\nextF.csv", row.names = FALSE)
```

```{r}
t.test(Date1$Percentage_Change,Date2$Percentage_Change)

# 	Welch Two Sample t-test
# 
# data:  Date1$Percentage_Change and Date2$Percentage_Change
# t = 2.4356, df = 228.86, p-value = 0.01563
# alternative hypothesis: true difference in means is not equal to 0
# 95 percent confidence interval:
#  0.001470546 0.013926242
# sample estimates:
#    mean of x    mean of y 
#  0.003820242 -0.003878152 


chisq.test(Date1$Percentage_Change,Date2$Percentage_Change)
# Pearson's Chi-squared test
# 
# data:  Date1$Percentage_Change and Date2$Percentage_Change
# X-squared = 11772, df = 11664, p-value = 0.2391
```

```{r add vix}
vix <-read.csv("^VIX.csv")

# lastvix <- vix[is.element(as.Date(vix$Date),as.Date(Date1$Date)),]
# nextvix <- vix[is.element(as.Date(vix$Date),as.Date(Date2$Date)),]

vix <- vix[,c(1,6)]
vix$Date <- as.Date(vix$Date)

lastF <- merge(Date1,vix, by='Date')
nextF <- merge(Date2,vix, by='Date')

colnames(lastF) <- c("Date","Percentage_Change","VIX")
colnames(nextF) <- c("Date","Percentage_Change","VIX")

```
```{r}
# lastFriday's vix trend
hist(lastF$VIX)
```

```{r}
# nextFriday's vix trend
hist(nextF$VIX)
```

```{r}
# add vixlevel
# define vexlevel as 'extreme','high','median' and 'low
lastF$vixLevel <- 0
nextF$vixLevel <- 0
colnames(lastF)[4] <- "vixlevel"
colnames(nextF)[4] <- "vixlevel"


f <- function(n,c1,c2) {
  for (i in 1:n)
  if(c1[i] >= 30){
    c2[i] <- "extreme"
  } else if (c1[i] < 30 & c1[i] >= 20){
    c2[i] <- "high"
  } else if (c1[i] < 20 & c1[i] >= 12){
    c2[i] <- "median"
  } else if(c1[i] < 12){
    c2[i] <- "low"
  }
  return (c2)
}


lastF$vixlevel <- f(nrow(lastF), lastF$VIX, lastF$vixlevel)
nextF$vixlevel <- f(nrow(nextF), nextF$VIX, nextF$vixlevel)
```

```{r}
# lastF's SP500 Percentage Change by vixlevel
ggplot(lastF, aes(x=Date, y=Percentage_Change, fill=vixlevel)) + 
  geom_bar(stat = 'identity')
```

```{r}
# nextF's SP500 Percentage Change by vixlevel
ggplot(nextF, aes(x=Date, y=Percentage_Change, fill=vixlevel)) + 
  geom_bar(stat = 'identity')
```


```{r}
# only pick vixlevel = 'median' and compare percentage change
lastF1 <- lastF %>% filter(vixlevel == 'median')
nextF1 <- nextF %>% filter(vixlevel == 'median')

t.test(lastF1$Percentage_Change,nextF1$Percentage_Change)
# 	Welch Two Sample t-test
# 
# data:  lastF1$Percentage_Change and nextF1$Percentage_Change
# t = 3.6054, df = 104.61, p-value = 0.0004793
# alternative hypothesis: true difference in means is not equal to 0
# 95 percent confidence interval:
#  0.004448934 0.015323341
# sample estimates:
#    mean of x    mean of y 
#  0.005976128 -0.003910010 

```

```{r}
# pick vixlevel = 'median' and 'low' and compare percentage change
lastF2 <- lastF %>% filter(vixlevel == 'median' | vixlevel == 'low')
nextF2 <- nextF %>% filter(vixlevel == 'median' | vixlevel == 'low')

t.test(lastF2$Percentage_Change,nextF2$Percentage_Change)
# Welch Two Sample t-test
# 
# data:  lastF2$Percentage_Change and nextF2$Percentage_Change
# t = 3.7024, df = 131.43, p-value = 0.0003132
# alternative hypothesis: true difference in means is not equal to 0
# 95 percent confidence interval:
#  0.004035773 0.013296200
# sample estimates:
#    mean of x    mean of y 
#  0.005915681 -0.002750306 
```