---
title: "Untitled"
author: "Maggie Sha"
date: "2020/12/6"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quantmod)
library(RcppBDT)
library(tidyverse)
library(timeDate)
library(lubridate)
library(gridExtra)
library(ggplot2)
```


```{r cars}
# read data
# this S&P500 index data is from Yahoo Finance from year 1990 to 2020.

GSPC <- read.csv("^GSPC.csv")

```

```{r}
# calculate percentage change of every day

for(i in 1: nrow(GSPC)){
  if (i == 1){
    GSPC$percentage_change[i] <- 0
  } else {
  GSPC$percentage_change[i] <- (GSPC$Adj.Close[i] - GSPC$Adj.Close[i-1]) / GSPC$Adj.Close[i-1]
  }
}

```


```{r}

# use function to redo this part

# f <- function(month, year){
#   witch <- getNthDayOfWeek(third, Fri, month, year)
#   Witch1 <- Witch-1
#   Witch2 <- Witch-2
#   Witch3 <- Witch-3
#   Witch4 <- Witch-4
#   Witch7 <- Witch-7
#   Witch8 <- Witch+3
#   Witch9 <- Witch+4
#   Witch10 <- Witch+5
#   Witch11 <- Witch+6
#   Witch12 <- Witch+7
#   cbind.data.frame(Witch,Witch1,Witch2,Witch3,Witch4,Witch7,Witch8,Witch9,Witch10,Witch11,Witch12)
# }
# 
# for (i in 1990:2020){
#   Mar <- f(3,i)
#   
#   Jun <- f(6,i)
#   
#   Sep <- f(9,i)
#   
#   
#   Dec <- f(12,i)
#   
#   
#   if (i == 1990){
#     quad_witching_date <- cbind.data.frame(Mar,Jun,Sep,Dec)
#   }
#   else{
#     quad_witching_date <- rbind.data.frame(quad_witching_date, cbind.data.frame(Mar,Jun,Sep,Dec))
#   }
# }

for (i in 1990:2020){
  Mar <- getNthDayOfWeek(third, Fri, 3, i)
  Mar1 <- Mar-1
  Mar2 <- Mar-2
  Mar3 <- Mar-3
  Mar4 <- Mar-4
  Mar7 <- Mar-7
  Mar8 <- Mar+3
  Mar9 <- Mar+4
  Mar10 <- Mar+5
  Mar11 <- Mar+6
  Mar12 <- Mar+7
  
  Jun <- getNthDayOfWeek(third, Fri, 6, i)
  Jun1 <- Jun-1
  Jun2 <- Jun-2
  Jun3 <- Jun-3
  Jun4 <- Jun-4
  Jun7 <- Jun-7
  Jun8 <- Jun+3
  Jun9 <- Jun+4
  Jun10 <- Jun+5
  Jun11 <- Jun+6
  Jun12 <- Jun+7
  
  Sep <- getNthDayOfWeek(third, Fri, 9, i)
  Sep1 <- Sep-1
  Sep2 <- Sep-2
  Sep3 <- Sep-3
  Sep4 <- Sep-4
  Sep7 <- Sep-7
  Sep8 <- Sep+3
  Sep9 <- Sep+4
  Sep10 <- Sep+5
  Sep11 <- Sep+6
  Sep12 <- Sep+7
  
  
  Dec <- getNthDayOfWeek(third, Fri, 12, i)
  Dec1 <- Dec-1
  Dec2 <- Dec-2
  Dec3 <- Dec-3
  Dec4 <- Dec-4
  Dec7 <- Dec-7
  Dec8 <- Dec+3
  Dec9 <- Dec+4
  Dec10 <- Dec+5
  Dec11 <- Dec+6
  Dec12 <- Dec+7
  
  
  if ( i == 1990){
    quad_witching_date <- cbind.data.frame(Mar1,Mar,Mar2,Mar4,Mar3,Mar7,Mar8,Mar9,Mar10,Mar11,Mar12,Jun1,Jun,Jun2,Jun3,Jun4,Jun7,Jun8,Jun9,Jun10,Jun11,Jun12,Sep1,Sep,Sep2,Sep3,Sep4,Sep7,Sep8,Sep9,Sep10,Sep11,Sep12,Dec1,Dec,Dec2,Dec3,Dec4,Dec7,Dec8,Dec9,Dec10,Dec11,Dec12)
  }
  else{
    quad_witching_date <- rbind.data.frame(quad_witching_date, cbind.data.frame(Mar1,Mar,Mar2,Mar3,Mar4,Mar7,Mar8,Mar9,Mar10,Mar11,Mar12,Jun1,Jun,Jun2,Jun3,Jun4,Jun7,Jun8,Jun9,Jun10,Jun11,Jun12,Sep1,Sep,Sep2,Sep3,Sep4,Sep7,Sep8,Sep9,Sep10,Sep11,Sep12,Dec1,Dec,Dec2,Dec3,Dec4,Dec7,Dec8,Dec9,Dec10,Dec11,Dec12))
  }
}
quad_witching_date
quad_witching <- data.frame(day = c(quad_witching_date[,'Mar1'],quad_witching_date[,'Mar'], quad_witching_date[,'Mar2'],quad_witching_date[,'Mar3'],quad_witching_date[,'Mar4'],quad_witching_date[,'Mar7'],quad_witching_date[,'Mar8'],quad_witching_date[,'Mar9'],quad_witching_date[,'Mar10'],quad_witching_date[,'Mar11'],quad_witching_date[,'Mar12'],quad_witching_date[,'Jun1'],quad_witching_date[,'Jun'], quad_witching_date[,'Jun2'],quad_witching_date[,'Jun3'],quad_witching_date[,'Jun4'],quad_witching_date[,'Jun7'],quad_witching_date[,'Jun8'],quad_witching_date[,'Jun9'],quad_witching_date[,'Jun10'],quad_witching_date[,'Jun11'],quad_witching_date[,'Jun12'],quad_witching_date[,'Sep1'],quad_witching_date[,'Sep'], quad_witching_date[,'Sep2'],quad_witching_date[,'Sep3'],quad_witching_date[,'Sep4'],quad_witching_date[,'Sep7'],quad_witching_date[,'Sep8'],quad_witching_date[,'Sep9'],quad_witching_date[,'Sep10'],quad_witching_date[,'Sep11'],quad_witching_date[,'Sep12'],quad_witching_date[,'Dec1'],quad_witching_date[,'Dec'], quad_witching_date[,'Dec2'],quad_witching_date[,'Dec3'],quad_witching_date[,'Dec4'],quad_witching_date[,'Dec7'],quad_witching_date[,'Dec8'],quad_witching_date[,'Dec9'],quad_witching_date[,'Dec10'],quad_witching_date[,'Dec11'],quad_witching_date[,'Dec12']))
quad_witching$day<- as.Date(quad_witching$day)
quad_witching<-quad_witching[order(as.Date(quad_witching$day,format="%d/%m/%Y")),,drop=FALSE]


#write.csv(quad_witching,"D:\\MA675 FIDELITY\\tenDays.csv", row.names = FALSE)
```

```{r}
# join data only keep those on witching days and 5 days before, 5 days after the witching days
GSPC <- GSPC[is.element(as.Date(GSPC$Date),as.Date(quad_witching$day)),]

colnames(quad_witching) <- "Date"

# ignore other columns
GSPC <- GSPC[,-2:-5]
GSPC <- GSPC[-3]
GSPC$Date <- as.Date(GSPC$Date)
quad_witching$Date <- as.Date(quad_witching$Date )

with_missing <- full_join(GSPC,quad_witching)
with_missing <- with_missing[order(with_missing$Date),]


# function to get date and mean percentage change
for(i in 1:(nrow(with_missing) / 11)) {
  
  # mean of the first 5 days
  l <- c(with_missing$percentage_change[i*11-6], with_missing$percentage_change[i*11-7], with_missing$percentage_change[i*11-8],
              with_missing$percentage_change[i*11-9], with_missing$percentage_change[i*11-10])
  
  lmean <- mean(l, na.rm = TRUE)
  
  # mean of the next 5 days
  n <- c(with_missing$percentage_change[[i*11]], with_missing$percentage_change[i*11-1], with_missing$percentage_change[i*11-2],
              with_missing$percentage_change[i*11-3], with_missing$percentage_change[i*11-4])
  
  nmean <- mean(n, na.rm = TRUE)
  
  # use the first date to represent first 5 days
  d1 <- as.Date(with_missing$Date[i*11-10])
  
  # use the last date to represent next 5 days
  d2 <- as.Date(with_missing$Date[i*11])
  
  if (i == 1){
       lastF <- cbind.data.frame(lmean)
       Date1 <- cbind.data.frame(d1)
       nextF <- cbind.data.frame(nmean)
       Date2 <- cbind.data.frame(d2)
  } else {
      lastF <- rbind.data.frame(lastF,cbind.data.frame(lmean))
      Date1 <- rbind.data.frame(Date1,cbind.data.frame(d1))
      nextF <- rbind.data.frame(nextF,cbind.data.frame(nmean))
      Date2 <- rbind.data.frame(Date2,cbind.data.frame(d2))
  }
}

#combine date and mean percentage change
Date1 <- cbind(Date1,lastF)
colnames(Date1) <- c("Date","Percentage_Change")

Date2 <- cbind(Date2,nextF)
colnames(Date2) <- c("Date","Percentage_Change")
```

```{r}
#read VIX data
vix <-read.csv("^VIX.csv")

vix <- vix[,c(1,6)]
vix$Date <- as.Date(vix$Date)

#combine percentage change and vix by Date
lastF <- merge(Date1,vix, by='Date')
nextF <- merge(Date2,vix, by='Date')

colnames(lastF) <- c("Date","Percentage_Change","VIX")
colnames(nextF) <- c("Date","Percentage_Change","VIX")
```


```{r}
# add vixlevel
# define vexlevel as 'high' and 'low
lastF$vixLevel <- 0
nextF$vixLevel <- 0
colnames(lastF)[4] <- "vixlevel"
colnames(nextF)[4] <- "vixlevel"
 
 
f <- function(n,c1,c2) {
   for (i in 1:n)
   if(c1[i] >= 20){
     c2[i] <- "high"
   } else if (c1[i] < 20){
     c2[i] <- "low"
   } 
   return (c2)
 }
 
 
lastF$vixlevel <- f(nrow(lastF), lastF$VIX, lastF$vixlevel)
nextF$vixlevel <- f(nrow(nextF), nextF$VIX, nextF$vixlevel)
```


```{r}
# lastF's SP500 Percentage Change by vixlevel
lastF_high <- lastF %>% filter(vixlevel == "high")
lastF_low <- lastF %>% filter(vixlevel ==  "low")
 
high <- ggplot(lastF_high, aes(x=Date, y=Percentage_Change, fill=vixlevel)) + 
                   geom_bar(stat = 'identity') + 
                   labs(title = "Last Five Days Percentage Change")
 
 
group.colors <- c(medium = "#E7B800", low = "darkorchid2")
 
low <- ggplot(lastF_low, aes(x=Date, y=Percentage_Change, fill = vixlevel)) + 
                  geom_bar(stat = 'identity') + 
                  scale_fill_manual(values = group.colors) + 
                  labs(title = "Last Five Days Percentage Change")
 
 
```


```{r}
# nextF's SP500 Percentage Change by vixlevel
nextF_high <- nextF %>% filter(vixlevel == "high")
nextF_low <- nextF %>% filter(vixlevel == "low")

high2 <- ggplot(nextF_high, aes(x=Date, y=Percentage_Change, fill=vixlevel)) + 
                  geom_bar(stat = 'identity') + 
                  labs(title = "Next Five Days Percentage Change")

group.colors2 <- c(medium = "#E7B800", low = "darkorchid2")

low2 <- ggplot(nextF_low, aes(x=Date, y=Percentage_Change, fill = vixlevel)) + 
                  geom_bar(stat = 'identity') + 
                  scale_fill_manual(values = group.colors2) + 
                  labs(title = "Next Five Days Percentage Change")

#visualize
grid.arrange(high, high2)
grid.arrange(low, low2)
```


```{r}
# pick vixlevel = 'low' and compare percentage change
lastF2 <- lastF %>% filter(vixlevel == 'low')
nextF2 <- nextF %>% filter(vixlevel == 'low')

t.test(lastF2$Percentage_Change,nextF2$Percentage_Change)
# t = 3.4106, df = 132.04, p-value = 0.0008605

ks.test(lastF2$Percentage_Change,nextF2$Percentage_Change)
# D = 0.3901, p-value = 2.8e-05


```


```{r}
lastF2$group <- "last_five_days"
nextF2$group <- "next_five_days"
density <- rbind.data.frame(lastF2,nextF2)
density
```

```{r}
mu <- ddply(density, "group", summarise, grp.mean=mean(Percentage_Change * 100))
head(mu)
```

```{r}
# Density plot with mean lines
p <- ggplot(density, aes(x=Percentage_Change * 100, fill=group)) +
  geom_density(alpha = 0.2,size = 1)+
  geom_vline(data = mu,aes(xintercept=grp.mean, color=group),
             linetype=1, size = 1.2) +
  labs(x = "Percentage Change", title = "Comparison of last week and next week with VIX group \"low\"") 

p
```

```{r}
# pick vixlevel = 'high' and compare percentage change
lastF3 <- lastF %>% filter(vixlevel == 'high')
nextF3 <- nextF %>% filter(vixlevel == 'high')

t.test(lastF3$Percentage_Change,nextF3$Percentage_Change)
# t = 1.3928, df = 84.988, p-value = 0.1673

ks.test(lastF3$Percentage_Change,nextF3$Percentage_Change)
# D = 0.35972, p-value = 0.003343

```

```{r}
lastF3$group <- "last_five_days"
nextF3$group <- "next_five_days"
density2 <- rbind.data.frame(lastF3,nextF3)
density2
```


```{r}
mu2 <- ddply(density2, "group", summarise, grp.mean=mean(Percentage_Change * 100, na.rm=TRUE))
head(mu2)
```

```{r}
# Density plot with mean lines
p2 <- ggplot(density2, aes(x=Percentage_Change * 100, fill=group)) +
  geom_density(alpha = 0.2,size = 1)+
  geom_vline(data = mu2,aes(xintercept=grp.mean, color=group),
             linetype=1, size = 1.2) +
  labs(x = "Percentage Change", title = "Comparison of last week and next week with VIX group \"high\"") 

p2
```